// ============================================================
// CONSTANTES DO STUDENTNEST
// ============================================================

export const COLORS = {
  primary: '#1B4F72',
  primaryLight: '#2E86C1',
  primaryDark: '#154360',
  secondary: '#F39C12',
  secondaryLight: '#F9C74F',
  accent: '#27AE60',
  background: '#F8F9FA',
  surface: '#FFFFFF',
  surfaceSecondary: '#F1F3F5',
  text: '#1A1A2E',
  textSecondary: '#6C757D',
  textLight: '#ADB5BD',
  border: '#DEE2E6',
  error: '#E74C3C',
  errorLight: '#FADBD8',
  success: '#27AE60',
  successLight: '#D5F5E3',
  warning: '#F39C12',
  warningLight: '#FDEBD0',
  pending: '#F39C12',
  confirmed: '#27AE60',
  cancelled: '#E74C3C',
  completed: '#6C757D',
  white: '#FFFFFF',
  black: '#000000',
  overlay: 'rgba(0,0,0,0.5)',
};

export const FONTS = {
  regular: 400,
  medium: 500,
  semibold: 600,
  bold: 700,
};

export const SIZES = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  radius: 8,
  radiusMd: 12,
  radiusLg: 16,
  radiusXl: 24,
  radiusFull: 999,
};

export const PROPERTY_TYPES = [
  { value: 'room', label: 'Quarto', icon: 'bed-outline' },
  { value: 'studio', label: 'Kitnet', icon: 'home-outline' },
  { value: 'republic', label: 'República', icon: 'people-outline' },
  { value: 'apartment', label: 'Apartamento', icon: 'business-outline' },
] as const;

export const BOOKING_STATUS_LABELS: Record<string, string> = {
  pending: 'Pendente',
  confirmed: 'Confirmado',
  cancelled: 'Cancelado',
  completed: 'Concluído',
};

export const STRINGS = {
  appName: 'StudentNest',
  tagline: 'Moradia universitária sem complicação',
  loading: 'Carregando...',
  error: 'Algo deu errado. Tente novamente.',
  noResults: 'Nenhum resultado encontrado.',
  loginTitle: 'Bem-vindo de volta',
  loginSubtitle: 'Entre na sua conta',
  registerTitle: 'Criar conta',
  registerSubtitle: 'Junte-se ao StudentNest',
  emailLabel: 'E-mail',
  passwordLabel: 'Senha',
  nameLabel: 'Nome completo',
  loginBtn: 'Entrar',
  registerBtn: 'Criar conta',
  noAccount: 'Não tem conta? ',
  hasAccount: 'Já tem conta? ',
  signUp: 'Cadastre-se',
  signIn: 'Entrar',
  homeTitle: 'Encontre sua moradia',
  searchPlaceholder: 'Buscar cidade ou bairro...',
  nearUniversity: 'Próximo à sua universidade',
  topRated: 'Mais avaliados',
  republics: 'Repúblicas disponíveis',
  reserve: 'Reservar',
  contact: 'Contatar anfitrião',
  favorite: 'Favoritos',
  myBookings: 'Minhas reservas',
  editProfile: 'Editar perfil',
  logout: 'Sair',
  confirmLogout: 'Deseja sair da sua conta?',
  cancel: 'Cancelar',
  confirm: 'Confirmar',
  save: 'Salvar',
  perMonth: '/mês',
  months: 'meses',
  totalPrice: 'Preço total',
  checkIn: 'Entrada',
  duration: 'Duração',
  bookingConfirmed: 'Reserva enviada!',
  bookingPending: 'Aguardando confirmação do anfitrião.',
  stars: 'estrelas',
  reviews: 'avaliações',
  rules: 'Regras da casa',
  description: 'Descrição',
  amenities: 'Comodidades',
  location: 'Localização',
  hostInfo: 'Sobre o anfitrião',
  addProperty: 'Anunciar imóvel',
  myProperties: 'Meus imóveis',
  newProperty: 'Novo anúncio',
  propertyTitle: 'Título do imóvel',
  propertyType: 'Tipo de imóvel',
  propertyCity: 'Cidade',
  propertyNeighborhood: 'Bairro',
  propertyPrice: 'Preço por mês (R$)',
  propertyDescription: 'Descrição',
  propertyRules: 'Regras da casa',
  publishProperty: 'Publicar imóvel',
  pendingRequests: 'Solicitações pendentes',
  activeBookings: 'Reservas ativas',
  acceptBooking: 'Aceitar',
  rejectBooking: 'Recusar',
};
