// ============================================================
// DADOS MOCK PARA DESENVOLVIMENTO SEM SUPABASE
// Substitua pelas chamadas reais ao Supabase depois
// ============================================================

import { Property, Review, Booking, Profile, Conversation } from '../types';

export const MOCK_PHOTOS = [
  'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
  'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
  'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
  'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
  'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
  'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
];

export const MOCK_AVATARS = [
  'https://i.pravatar.cc/150?img=1',
  'https://i.pravatar.cc/150?img=2',
  'https://i.pravatar.cc/150?img=5',
  'https://i.pravatar.cc/150?img=8',
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    host_id: 'h1',
    title: 'Quarto aconchegante próximo à USP',
    description: 'Quarto mobiliado em casa compartilhada a 5 minutos da USP. Internet de alta velocidade, cozinha equipada e área de lazer. Ambiente tranquilo e seguro, ideal para estudar.',
    type: 'room',
    city: 'São Paulo',
    state: 'SP',
    neighborhood: 'Butantã',
    price_per_month: 950,
    min_stay_months: 6,
    max_guests: 1,
    is_active: true,
    rules: 'Sem pets, sem festas, limpeza compartilhada às quartas.',
    created_at: '2024-01-01',
    average_rating: 4.8,
    review_count: 23,
    photos: [
      { id: 'p1', property_id: '1', url: MOCK_PHOTOS[0], is_cover: true, order_index: 0 },
      { id: 'p2', property_id: '1', url: MOCK_PHOTOS[3], is_cover: false, order_index: 1 },
    ],
    host: {
      id: 'h1',
      full_name: 'Carlos Oliveira',
      avatar_url: MOCK_AVATARS[0],
      user_type: 'host',
      university_email: null,
      is_verified: true,
      bio: 'Proprietário há 5 anos, sempre disponível para ajudar.',
      phone: '11999999999',
      created_at: '2020-01-01',
    },
  },
  {
    id: '2',
    host_id: 'h2',
    title: 'República estudantil - UNICAMP',
    description: 'República com 4 quartos a 10 min da UNICAMP. Ambiente descontraído, festas permitidas nos fins de semana. Vaga em quarto duplo disponível imediatamente.',
    type: 'republic',
    city: 'Campinas',
    state: 'SP',
    neighborhood: 'Barão Geraldo',
    price_per_month: 750,
    min_stay_months: 3,
    max_guests: 1,
    is_active: true,
    rules: 'Respeitar horário de silêncio após 23h nos dias de semana.',
    created_at: '2024-02-01',
    average_rating: 4.5,
    review_count: 41,
    photos: [
      { id: 'p3', property_id: '2', url: MOCK_PHOTOS[1], is_cover: true, order_index: 0 },
      { id: 'p4', property_id: '2', url: MOCK_PHOTOS[4], is_cover: false, order_index: 1 },
    ],
    host: {
      id: 'h2',
      full_name: 'Mariana Santos',
      avatar_url: MOCK_AVATARS[1],
      user_type: 'host',
      university_email: null,
      is_verified: true,
      bio: 'Gerencio 2 repúblicas há 8 anos.',
      phone: '19988888888',
      created_at: '2019-06-01',
    },
  },
  {
    id: '3',
    host_id: 'h3',
    title: 'Kitnet mobiliada - Zona Sul SP',
    description: 'Kitnet totalmente mobiliada com cozinha compacta, banheiro privativo e área de serviço. Próxima à UNIFESP e metrô. Ideal para quem busca privacidade.',
    type: 'studio',
    city: 'São Paulo',
    state: 'SP',
    neighborhood: 'Vila Clementino',
    price_per_month: 1400,
    min_stay_months: 6,
    max_guests: 1,
    is_active: true,
    rules: 'Sem pets. Condomínio não permite barulho após 22h.',
    created_at: '2024-03-01',
    average_rating: 4.9,
    review_count: 12,
    photos: [
      { id: 'p5', property_id: '3', url: MOCK_PHOTOS[2], is_cover: true, order_index: 0 },
      { id: 'p6', property_id: '3', url: MOCK_PHOTOS[5], is_cover: false, order_index: 1 },
    ],
    host: {
      id: 'h3',
      full_name: 'Roberto Lima',
      avatar_url: MOCK_AVATARS[2],
      user_type: 'host',
      university_email: null,
      is_verified: false,
      bio: 'Moro no mesmo prédio, sempre por perto.',
      phone: '11977777777',
      created_at: '2022-03-01',
    },
  },
  {
    id: '4',
    host_id: 'h1',
    title: 'Apartamento 2 quartos - Belo Horizonte',
    description: 'Apartamento completo para dividir com outro estudante. 2 quartos, sala, cozinha e 2 banheiros. Condomínio com academia e piscina. Próximo à UFMG.',
    type: 'apartment',
    city: 'Belo Horizonte',
    state: 'MG',
    neighborhood: 'Pampulha',
    price_per_month: 1100,
    min_stay_months: 6,
    max_guests: 2,
    is_active: true,
    rules: 'Dividir contas de água e luz. Sem fumar dentro do apartamento.',
    created_at: '2024-01-15',
    average_rating: 4.6,
    review_count: 8,
    photos: [
      { id: 'p7', property_id: '4', url: MOCK_PHOTOS[4], is_cover: true, order_index: 0 },
      { id: 'p8', property_id: '4', url: MOCK_PHOTOS[0], is_cover: false, order_index: 1 },
    ],
    host: {
      id: 'h1',
      full_name: 'Carlos Oliveira',
      avatar_url: MOCK_AVATARS[0],
      user_type: 'host',
      university_email: null,
      is_verified: true,
      bio: 'Proprietário há 5 anos, sempre disponível para ajudar.',
      phone: '11999999999',
      created_at: '2020-01-01',
    },
  },
  {
    id: '5',
    host_id: 'h4',
    title: 'Quarto individual - Centro de Curitiba',
    description: 'Quarto individual em casa grande, bem localizado no centro de Curitiba. A 15 min da UFPR de ônibus. Internet, água e gás inclusos no valor.',
    type: 'room',
    city: 'Curitiba',
    state: 'PR',
    neighborhood: 'Centro',
    price_per_month: 820,
    min_stay_months: 3,
    max_guests: 1,
    is_active: true,
    rules: 'Sem animais. Limpeza das áreas comuns é responsabilidade de todos.',
    created_at: '2024-02-20',
    average_rating: 4.3,
    review_count: 16,
    photos: [
      { id: 'p9', property_id: '5', url: MOCK_PHOTOS[3], is_cover: true, order_index: 0 },
    ],
    host: {
      id: 'h4',
      full_name: 'Ana Paula Ferreira',
      avatar_url: MOCK_AVATARS[3],
      user_type: 'host',
      university_email: null,
      is_verified: true,
      bio: 'Moro na casa há 10 anos e adoro receber estudantes.',
      phone: '41966666666',
      created_at: '2021-08-01',
    },
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    booking_id: 'b1',
    reviewer_id: 's1',
    property_id: '1',
    rating: 5,
    comment: 'Lugar incrível! Muito tranquilo para estudar, anfitrião super atencioso. Recomendo demais!',
    created_at: '2024-03-15',
    reviewer: {
      id: 's1', full_name: 'Julia Mendes', avatar_url: MOCK_AVATARS[1],
      user_type: 'student', university_email: 'julia@usp.br', is_verified: true,
      bio: null, phone: null, created_at: '2023-09-01',
    },
  },
  {
    id: 'r2',
    booking_id: 'b2',
    reviewer_id: 's2',
    property_id: '1',
    rating: 5,
    comment: 'Melhor custo-benefício que encontrei em SP. Quarto limpo, internet boa e vizinhos respeitosos.',
    created_at: '2024-02-10',
    reviewer: {
      id: 's2', full_name: 'Pedro Alves', avatar_url: MOCK_AVATARS[2],
      user_type: 'student', university_email: 'pedro@usp.br', is_verified: true,
      bio: null, phone: null, created_at: '2023-08-01',
    },
  },
  {
    id: 'r3',
    booking_id: 'b3',
    reviewer_id: 's3',
    property_id: '1',
    rating: 4,
    comment: 'Muito bom no geral. Só falta um armário maior no quarto, mas o preço compensa.',
    created_at: '2024-01-25',
    reviewer: {
      id: 's3', full_name: 'Camila Rocha', avatar_url: MOCK_AVATARS[3],
      user_type: 'student', university_email: 'camila@usp.br', is_verified: false,
      bio: null, phone: null, created_at: '2023-07-01',
    },
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    property_id: '2',
    student_id: 'current_user',
    host_id: 'h2',
    status: 'confirmed',
    check_in: '2024-03-01',
    check_out: '2024-09-01',
    total_price: 4500,
    months: 6,
    created_at: '2024-02-15',
    property: MOCK_PROPERTIES[1],
  },
  {
    id: 'b2',
    property_id: '3',
    student_id: 'current_user',
    host_id: 'h3',
    status: 'pending',
    check_in: '2024-04-01',
    check_out: '2024-10-01',
    total_price: 8400,
    months: 6,
    created_at: '2024-03-20',
    property: MOCK_PROPERTIES[2],
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'c1',
    property_id: '1',
    student_id: 'current_user',
    host_id: 'h1',
    last_message_at: '2024-03-22T10:30:00',
    last_message: 'Olá! Ainda tem vaga disponível?',
    property: MOCK_PROPERTIES[0],
    host: MOCK_PROPERTIES[0].host,
  },
  {
    id: 'c2',
    property_id: '2',
    student_id: 'current_user',
    host_id: 'h2',
    last_message_at: '2024-03-21T15:00:00',
    last_message: 'Reserva confirmada! Bem-vindo à república 🏠',
    property: MOCK_PROPERTIES[1],
    host: MOCK_PROPERTIES[1].host,
  },
];

export const MOCK_HOST_BOOKINGS: Booking[] = [
  {
    id: 'hb1',
    property_id: '1',
    student_id: 's1',
    host_id: 'current_user',
    status: 'pending',
    check_in: '2024-04-01',
    check_out: '2024-10-01',
    total_price: 5700,
    months: 6,
    created_at: '2024-03-22',
    property: MOCK_PROPERTIES[0],
    student: {
      id: 's1', full_name: 'Julia Mendes', avatar_url: MOCK_AVATARS[1],
      user_type: 'student', university_email: 'julia@usp.br', is_verified: true,
      bio: null, phone: null, created_at: '2023-09-01',
    },
  },
  {
    id: 'hb2',
    property_id: '1',
    student_id: 's4',
    host_id: 'current_user',
    status: 'confirmed',
    check_in: '2024-01-01',
    check_out: '2024-07-01',
    total_price: 5700,
    months: 6,
    created_at: '2023-12-10',
    property: MOCK_PROPERTIES[0],
    student: {
      id: 's4', full_name: 'Lucas Fernandes', avatar_url: MOCK_AVATARS[0],
      user_type: 'student', university_email: 'lucas@usp.br', is_verified: true,
      bio: null, phone: null, created_at: '2023-06-01',
    },
  },
];
